name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Azure VM and Deploy Containers
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
