name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test backend
        run: |
          cd backend
          docker build -t backend:latest .
          docker run --rm backend:latest npm test

      - name: Build and test frontend
        run: |
          cd frontend
          docker build -t frontend:latest .
          docker run --rm frontend:latest npm test

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag and Push Backend Image
        run: |
          docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Tag and Push Frontend Image
        run: |
          docker tag frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
